version: '3.4'

services:

  app-infrastructure-apigateway:
    image: ${DockerHub_Registry}/app-infrastructure-apigateway:${DockerImage_Tag}
    build:
      context: .
      dockerfile: apps-common/Apps.Base.APIGateway/Dockerfile

  app-microservice-basic-api:
    image: ${DockerHub_Registry}/app-microservice-basic-api:${DockerImage_Tag}
    build:
      context: .
      dockerfile: apps-legacy/ApiServer/Dockerfile

  app-microservice-oms-api:
    image: ${DockerHub_Registry}/app-microservice-oms-api:${DockerImage_Tag}
    build:
      context: .
      dockerfile: apps-oms/Apps.OMS.Service/Dockerfile
