version: '3.4'

services:
  apps.base.apigateway:
    image: ${DOCKER_REGISTRY}appsbaseapigateway
    build:
      context: .
      dockerfile: apps-common/Apps.Base.APIGateway/Dockerfile
    ports:
      - "1881:80"