version: '3.4'

services:
  apps.base.apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  apps.basic.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  apps.morejee.service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

