version: '3.4'

services:
  dmzpostgresdb:
    container_name: dmzpostgresdb_c
    ports:
      - "1990:5432"
      
  dmzapiserver:
    container_name: dmzapiserver_c
    ports:
      - "1991:80"
    environment:
      # JwtSettings
      - JwtSettings:Issuer=damaozhu.com.cn
      - JwtSettings:Audience=damaozhu.com.cn
      - JwtSettings:SecretKey=damaozhu-dev-test-app
      - JwtSettings:ExpiresDay=1
      # ConnectionString
      - ConnectionString=Server=dmzpostgresdb;Port=5432;Database=dmz;User Id=${PostgresDB_User};Password=${PostgresDB_Password}
      # Plugins
      - Plugins:OrderViewer=http://share.damaozhu.com.cn/dmz/order/viewer
      - Plugins:MediaShare=http://share.damaozhu.com.cn/dmz/share/panorama
    volumes:
      - "/var/bamboo/dmzapiserver/logs:/app/logs"
      - "/var/bamboo/dmzapiserver/wwwroot/upload:/app/wwwroot/upload"

  dmztoolsite_for_dmzapiserver:
    container_name: dmztoolsite_for_dmzapiserver_c
    ports:
      - "1992:3000"
    environment:
      - SERVER=http://testapi.damaozhu.com.cn

  dmzapiserver_ehome:
    container_name: dmzapiserver_ehome_c
    ports:
      - "1993:80"
    environment:
      # JwtSettings
      - JwtSettings:Issuer=damaozhu.com.cn
      - JwtSettings:Audience=damaozhu.com.cn
      - JwtSettings:SecretKey=damaozhu-ehome-test-app
      - JwtSettings:ExpiresDay=1
      # ConnectionString
      - ConnectionString=Server=dmzpostgresdb;Port=5432;Database=dmz_ehome;User Id=${PostgresDB_User};Password=${PostgresDB_Password}
      # Plugins
      - Plugins:OrderViewer=http://kennshare.damaozhu.com.cn/dmz/order/viewer
      - Plugins:MediaShare=http://kennshare.damaozhu.com.cn/dmz/share/panorama
    volumes:
      - "/var/bamboo/dmzapiserver_ehome/logs:/app/logs"
      - "/var/bamboo/dmzapiserver/wwwroot/upload:/app/wwwroot/upload"
      
  dmztoolsite_for_dmzapiserver_ehome:
    container_name: dmztoolsite_for_dmzapiserver_ehome_c
    ports:
      - "1994:3000"
    environment:
      - SERVER=http://kennapi.damaozhu.com.cn